version: 2

refs:
  container: &container
    docker:
      - image: node:8.11
    working_directory: ~/repo
  steps:
    - &Install_Dependencies
      run:
        name: Install Dependencies
        command: |
          node -v && npm -v && yarn -v
          yarn install --pure-lockfile
          git clone https://github.com/sstephenson/bats.git
          cd bats
          sudo ./install.sh /usr/local
    - &Tests
      run:
        name: Tests
        command: yarn test

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *Install_Dependencies
      - *Tests

  master:
    <<: *container
    steps:
      - checkout
      - *Install_Dependencies
      - *Tests
      - run:
          name: Publish
          command: npx semantic-release

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
  master:
    jobs:
      - master:
          filters:
            branches:
              only: master
